<a href="https://colab.research.google.com/github/saroj321r-cmd/Data-Science-/blob/main/Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

n = int(input());
price =[];
for i in range(n):
  x= int(input())
  price.append(x)

grocery = np.array(price)

print("Grocery Prices:", grocery)
print("Total price:",np.sum(grocery))
print("Average:",np.mean(grocery))
print("Maximum Price:",np.max(grocery))
print("Minimum Price :",np.min(grocery))
print("Standard Deviation:",np.std(grocery))


3
1
56
34
Grocery Prices: [ 1 56 34]
Total price: 91
Average: 30.333333333333332
Maximum Price: 56
Minimum Price : 1
Standard Deviation: 22.60285134421958


In [2]:
import numpy as np

# create a 5*5 matrix of random integers

a = np.random.randint(1,90,(5,5))
print(a)

[[21 53 41  9 86]
 [24 65 51 79 31]
 [60 30 33 69 69]
 [10 22 60  2 57]
 [14 61 17 42 16]]


In [5]:
# find mean of values of row and column wise

import numpy as np

a = np.random.randint(1,100,(5,5))
print(a)
print(np.mean(a,axis=1))#row
print(np.mean(a,axis=0))#column

[[47 49  1 63 62]
 [30 51 47 71 39]
 [93 33 53  1 19]
 [61 26 74 20 10]
 [60 32 72  2 25]]
[44.4 47.6 39.8 38.2 38.2]
[58.2 38.2 49.4 31.4 31. ]


In [10]:
#replece even number by -1

b= np.random.randint(1,20,5)
print(b)

b[b%2==0]=-1
print(b)

c= np.where(b%2==0,-1,b)
print(c)

[ 1 15 10  6 11]
[ 1 15 -1 -1 11]
[ 1 15 -1 -1 11]


In [20]:
#sort the array row and column wise

import numpy as np

a = np.random.randint(1,100,(5,5))
print(a)

print(np.sort(a, axis=1))
print(np.sort(a,axis=0))

#find row and column wise sum
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

#count the number of negative in each column

c = np.array([-2,6,-1,8,45])
count = len(c[c < 0])

print(count)

[[26 15 61 18 86]
 [24 34 52 49 19]
 [28 75 19  7 22]
 [75 75 74 68 77]
 [72 21 82 75 44]]
[[15 18 26 61 86]
 [19 24 34 49 52]
 [ 7 19 22 28 75]
 [68 74 75 75 77]
 [21 44 72 75 82]]
[[24 15 19  7 19]
 [26 21 52 18 22]
 [28 34 61 49 44]
 [72 75 74 68 77]
 [75 75 82 75 86]]
[206 178 151 369 294]
[225 220 288 217 248]
2


In [21]:
a = np.array([-3,8,9,93,-1,-4])
count=0
b= np.sum(np.where(a<0,1,0))
print(b)

3


In [29]:
# create a 5*5 array(stock level)

stock = np.random.randint(1,90,(5,5))
print(stock)

# create another 5*5 (demand)

demand = np.random.randint(1,90,(5,5))
print(demand)

# remaining stock = stock - demand

remaining_stock = stock - demand
print(remaining_stock)

# neg value - 0 (out of stock)
outof_stock = np.where(remaining_stock<0,0,remaining_stock)
print(outof_stock)

# total shortage

total_shortage = np.sum(np.where(remaining_stock<0,remaining_stock* -1,0),axis =0)
print(total_shortage)

#  product with zero stock

zero_stock =np.sum(np.where(outof_stock==0,1,0),axis = 0)
print(zero_stock)

# sort each row and column on remaining stock

print(np.sort(remaining_stock,axis = 1))
print(np.sort(remaining_stock,axis=0))

[[27 74 11 40 67]
 [55 60 40 21 74]
 [ 1 46 13  7 16]
 [35 31 47 59 27]
 [64 20 10 55 44]]
[[72 85 46  1 63]
 [61 87 66 36 63]
 [66  3  8 86 84]
 [18 41 36 61 31]
 [36 58 67 84 39]]
[[-45 -11 -35  39   4]
 [ -6 -27 -26 -15  11]
 [-65  43   5 -79 -68]
 [ 17 -10  11  -2  -4]
 [ 28 -38 -57 -29   5]]
[[ 0  0  0 39  4]
 [ 0  0  0  0 11]
 [ 0 43  5  0  0]
 [17  0 11  0  0]
 [28  0  0  0  5]]
[116  86 118 125  72]
[3 4 3 4 2]
[[-45 -35 -11   4  39]
 [-27 -26 -15  -6  11]
 [-79 -68 -65   5  43]
 [-10  -4  -2  11  17]
 [-57 -38 -29   5  28]]
[[-65 -38 -57 -79 -68]
 [-45 -27 -35 -29  -4]
 [ -6 -11 -26 -15   4]
 [ 17 -10   5  -2   5]
 [ 28  43  11  39  11]]
